scrape_configs:

  - job_name: gotti-server
    scrape_interval: 5s
    static_configs:
      #- targets: ['localhost:9000']
# если это не работает, когда вы запускаете приложение в контейнере (не на хост-компьютере), попробуйте использовать:
      - targets: ['host.docker.internal:9000']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
